### ISSUE TITLE
Funciones

### ISSUE THREAD

**Issue by Nidev-lab** [goarguello/project3-rollingcodeschool#35]
Bueenas! como va? estuve mirando su  codigo y tengo este error.

![image](https://user-images.githubusercontent.com/53904695/201888883-d1d2687f-4415-426f-8b74-c955a93b5809.png)

se agregaron alumnos a cada uno de los cursos, como se modifica el contador de alumnos por materias? 

Cualquier cosita podes contactarme a [nicogonzalez2008@gmail.com](mailto:nicogonzalez2008@gmail.com) o por el slack de RollingCode

**Comment by Dan1el-aguilar** [comment]
Nico capo como va?, para agregar Alumnos a una materia tenes que ir al crud de materias y hacer click en una y agregar un alumno de la lista
(disculpa que no este graficado eso o por lo menos que te diga)

**Comment by Dan1el-aguilar** [comment]
comentarios eliminados, si haces click tambien en la cantidad de alumnos( de la imagen) te muestra los alumnos
